import type { DirectorPlan } from "./types.ts";

/** Canonical three-shot plan used to detect compiler contract regressions. */
export const GOLDEN_DIRECTOR_PLAN: DirectorPlan = {
  schemaVersion: 1,
  enabled: true,
  sourceAssetId: "golden-first",
  canvas: { sourceWidth: 1920, sourceHeight: 1080 },
  cameraRig: {
    id: "golden-rig",
    sensorPreset: "neutral",
    lensPreset: "neutral",
  },
  subjects: [{
    id: "golden-truck",
    label: "Fruit truck",
    sourceAssetId: "golden-first",
    region: { type: "box", x: 0.12, y: 0.36, width: 0.28, height: 0.32 },
  }],
  motions: [
    {
      id: "golden-curve",
      targetType: "subject",
      targetId: "golden-truck",
      kind: "translate",
      path: [{ x: 0.2, y: 0.62 }, { x: 0.48, y: 0.34 }, { x: 0.82, y: 0.52 }],
      intensity: 0.75,
      start: 0,
      end: 1,
      easing: "ease_in_out",
      order: 1,
      actionLabel: "Follow the curved road",
    },
    {
      id: "golden-dolly",
      targetType: "camera",
      kind: "dolly",
      direction: "in",
      intensity: 0.6,
      start: 0,
      end: 0.8,
      easing: "ease_in",
      order: 1,
    },
    {
      id: "golden-orbit",
      targetType: "camera",
      kind: "orbit",
      direction: "left",
      intensity: 0.5,
      start: 0.3,
      end: 1,
      easing: "ease_out",
      order: 2,
    },
  ],
  keyframes: [
    { id: "golden-key-first", assetId: "golden-first", role: "first", time: 0 },
    { id: "golden-key-last", assetId: "golden-last", role: "last", time: 1 },
  ],
  shots: [
    {
      id: "golden-shot-one",
      order: 1,
      durationSeconds: 2,
      promptFragment: "The truck enters on a curved road.",
      motionIds: ["golden-curve"],
      keyframeIds: ["golden-key-first"],
      speed: "linear",
    },
    {
      id: "golden-shot-two",
      order: 2,
      durationSeconds: 2,
      promptFragment: "Move close while orbiting the truck.",
      motionIds: ["golden-dolly", "golden-orbit"],
      keyframeIds: [],
      speed: "slow_motion",
    },
    {
      id: "golden-shot-three",
      order: 3,
      durationSeconds: 2,
      promptFragment: "Finish on the product mark.",
      motionIds: [],
      keyframeIds: ["golden-key-last"],
      speed: "speed_up",
    },
  ],
  updatedAt: "2026-09-04T00:00:00.000Z",
};
